/*
Copyright 2014
Authors : Pekka Maksimainen
Website : http://graphmap.net
 */
package net.graphmap.mapper;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFileChooser;
import org.openide.util.NbPreferences;
import org.openide.windows.WindowManager;

/**
 * @author Pekka Maksimainen
 */
public class TileExporterPanel extends javax.swing.JPanel {
    
    final String LAST_PATH = "TileExporterPanel_Last_Path";
    private File path;
    private TileExporter exporter;
    private boolean isExportJson;
    
    public TileExporterPanel() {
        initComponents();
        
        browseButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFileChooser fileChooser = new JFileChooser(directoryTextField.getText());
                fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                int result = fileChooser.showSaveDialog(WindowManager.getDefault().getMainWindow());
                if (result == JFileChooser.APPROVE_OPTION) {
                    path = fileChooser.getSelectedFile();
                    directoryTextField.setText(path.getAbsolutePath());
                }
            }
        });
    }

    public void setup(TileExporter exporter) {
        this.exporter = exporter;
        heightTextField.setText(Integer.toString(exporter.getHeight()));
        widthTextField.setText(Integer.toString(exporter.getWidth()));
        levelsTextField.setText(Integer.toString(exporter.getLevels()));
        path = new File(NbPreferences.forModule(TileExporterPanel.class).get(LAST_PATH, System.getProperty("user.home") + File.separator + "tiles"));
        directoryTextField.setText(path.getAbsolutePath());
        exportJsonCheckBox.setSelected(exporter.isExportJson());
    }

    public void unsetup(boolean update) {
        if (update) {
            try {
                NbPreferences.forModule(TileExporterPanel.class).put(LAST_PATH, directoryTextField.getText());
                exporter.setWidth(Integer.parseInt(widthTextField.getText()));
                exporter.setHeight(Integer.parseInt(heightTextField.getText()));
                exporter.setLevels(Integer.parseInt(levelsTextField.getText()));
                exporter.setDirectory(directoryTextField.getText());
                exporter.setExportJson(exportJsonCheckBox.isSelected());
            } catch (Exception ex) {
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        widthDescriptionLabel = new javax.swing.JLabel();
        widthTextField = new javax.swing.JTextField();
        widthLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        heightTextField = new javax.swing.JTextField();
        heightDescriptionLabel = new javax.swing.JLabel();
        levelsLabel = new javax.swing.JLabel();
        labelHpx1 = new javax.swing.JLabel();
        directoryTextField = new javax.swing.JTextField();
        directoryLabel = new javax.swing.JLabel();
        levelsTextField = new javax.swing.JTextField();
        levelsDescriptionLabel = new javax.swing.JLabel();
        browseButton = new javax.swing.JButton();
        exportJsonCheckBox = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(325, 145));

        widthDescriptionLabel.setText("px (eg. 256)"); // NOI18N

        widthTextField.setText(org.openide.util.NbBundle.getMessage(TileExporterPanel.class, "TileExporterPanel.widthTextField.text")); // NOI18N
        widthTextField.setName("width"); // NOI18N

        widthLabel.setText("Width:"); // NOI18N

        heightLabel.setText("Height:"); // NOI18N

        heightTextField.setText(org.openide.util.NbBundle.getMessage(TileExporterPanel.class, "TileExporterPanel.heightTextField.text")); // NOI18N
        heightTextField.setName("height"); // NOI18N

        heightDescriptionLabel.setText("px (eg. 256)"); // NOI18N

        levelsLabel.setText("Levels:"); // NOI18N

        directoryTextField.setText(org.openide.util.NbBundle.getMessage(TileExporterPanel.class, "TileExporterPanel.directoryTextField.text")); // NOI18N
        directoryTextField.setToolTipText(org.openide.util.NbBundle.getMessage(TileExporterPanel.class, "TileExporterPanel.directoryTextField.toolTipText")); // NOI18N
        directoryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directoryTextFieldActionPerformed(evt);
            }
        });

        directoryLabel.setText("Directory name"); // NOI18N

        levelsTextField.setText(org.openide.util.NbBundle.getMessage(TileExporterPanel.class, "TileExporterPanel.levelsTextField.text")); // NOI18N
        levelsTextField.setName("width"); // NOI18N

        levelsDescriptionLabel.setText("(eg. 3)"); // NOI18N
        levelsDescriptionLabel.setToolTipText(org.openide.util.NbBundle.getMessage(TileExporterPanel.class, "TileExporterPanel.levelsDescriptionLabel.toolTipText")); // NOI18N

        browseButton.setText(org.openide.util.NbBundle.getMessage(TileExporterPanel.class, "TileExporterPanel.browseButton.text")); // NOI18N

        exportJsonCheckBox.setText(org.openide.util.NbBundle.getMessage(TileExporterPanel.class, "TileExporterPanel.exportJsonCheckBox.text")); // NOI18N
        exportJsonCheckBox.setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heightLabel)
                            .addComponent(levelsLabel)
                            .addComponent(widthLabel))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(heightDescriptionLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(widthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(widthDescriptionLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(levelsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(levelsDescriptionLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelHpx1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(directoryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(directoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseButton))
                    .addComponent(exportJsonCheckBox))
                .addGap(273, 273, 273))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(labelHpx1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(widthDescriptionLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(widthLabel)
                                .addComponent(widthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heightDescriptionLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(heightLabel)
                                .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(levelsLabel)
                            .addComponent(levelsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(levelsDescriptionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(directoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(directoryLabel)
                            .addComponent(browseButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(exportJsonCheckBox))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void directoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directoryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_directoryTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JLabel directoryLabel;
    private javax.swing.JTextField directoryTextField;
    private javax.swing.JCheckBox exportJsonCheckBox;
    private javax.swing.JLabel heightDescriptionLabel;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JTextField heightTextField;
    private javax.swing.JLabel labelHpx1;
    private javax.swing.JLabel levelsDescriptionLabel;
    private javax.swing.JLabel levelsLabel;
    private javax.swing.JTextField levelsTextField;
    private javax.swing.JLabel widthDescriptionLabel;
    private javax.swing.JLabel widthLabel;
    private javax.swing.JTextField widthTextField;
    // End of variables declaration//GEN-END:variables
}
